src/accounts/urls.py
from django.conf.urls import url
from .views import (LoginView, logout_view, RegisterView,
                    GuestRegisterView, AccountHomeView, AccountEmailActivateView,
                    UserDetailUpdateView)
from products.views import UserProductHistoryView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest-register'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
]

src/cart/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^api/$', cart_detail_api_view, name='cart-api'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^checkout/success$',checkout_done_view, name='success'),
    url(r'^checkout/$',checkout_home, name='checkout'),

]

src/mainwebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from .views import home_page, about_page, contact_page
from billing.views import payment_method_view, payment_method_create_view

from marketing.views import MarketingPreferenceUpdateView, MailChimpWebhookView

from addresses.views import (AddressListView, AddressCreateView,
                             AddressUpdateView, checkout_address_reuse_view,
                             checkout_address_create_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls', namespace='password')),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhook/mailchimp/$', MailChimpWebhookView.as_view(), name='webhook-mailchimp'),
    url(r'^cart/', include("cart.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_create_view, name='billing-payment-method-endpoint'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.conf.urls import url

from .views import (
        OrderListView,
        OrderDetailView
        )

urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='list'),
    url(r'^(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='detail'),
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
      integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
      crossorigin="anonymous">
<!--Font Awesome CSS-->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!--Jquery Confirm CSS-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
<!--Stripe related CSS-->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

src/templates/base/forms.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-12 col-md-8 mx-auto bg-light text-center py-3" >
        {% if title %}
        <h1 class="my-3"> {{title}} </h1>
        {% endif %}
        <form class="col-12 col-md-8 mx-auto " method="post"
              action=" {% if action_url %} {{action_url}}{% endif %}">
            {% csrf_token %}
            {% if next_url %}
            <input type="hidden" name="next" value="{{ next_url}}">
            {% endif %}
             {{ form.as_p }}
            <div class="col-sm-8 col-lg-6 mx-auto">
                <button type="submit" class="btn btn-primary btn-block"> Save </button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/base/js.html
{% load static %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
<!-- jQuery Confirm -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- stripe related -->
<script src="https://js.stripe.com/v3/"></script>

<!-- JsRender JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.90/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

<!-- mainWebsite js -->
<script src="{% static 'js/mainwebsite.js' %}"></script>

<!-- django securetoken for ajax js -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- django securetoken for ajax js -->
<script src="{% static 'js/billing.js' %}"></script>

src/templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'>
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>
  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>
    </form>
</script>
{% endverbatim %}

src/templates/base/navbar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url%}
{% url 'products:list' as products_url%}
{% url 'account:login' as login_url %}
{% url 'account:logout' as logout_url %}
{% url 'account:register' as register_url %}
{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
<div class="container">
  <a class="navbar-brand" href="{{ home_url }}">
      <img src="{% static 'img/logo.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      {% if brand_name %} {{ brand_name }} {% else %} one stop shop!{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item{% if request.path == home_url %} active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item{% if request.path == contact_url %} active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item{% if request.path == products_url %} active{% endif %}">
        <a class="nav-link" href="{{ products_url }}">Products</a>
      </li>
    {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item{% if request.path == account_url %} active{% endif %} " href="{{ account_url }}">Home</a>
            <a class="dropdown-item" href="#">Billing</a>
            <a class="dropdown-item" href="#">Preferences</a>
            <a class="dropdown-item" href="#">History</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
        </div>
    {% else %}
        <li class="nav-item{% if request.path == login_url %} active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
        <li class="nav-item{% if request.path == register_url %} active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
        </li>
    {% endif %}
    </ul>
    {% include 'search/snippets/search-form.html' %}
    <a class=" {% if request.path == cart_url %}active text-light {% else %} text-muted {% endif %}"
       href="{{ cart_url }}"><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
        {% if request.session.cart_products >= 0 %}
        <span class="badge badge-primary cart-count"
              style=" top: -18px; left: -15px; position: relative; height: 20px; width: 20px;
              line-height: 15px; border-radius: 50%; font-size: 0.7em;">
            {{request.session.cart_products}}</span>
        {% endif %}
    </a>
  </div>
</div>
</nav>