src/accounts/passwords/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^password/change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password/change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password/reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password/reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

src/accounts/urls.py
from django.conf.urls import url
from .views import (LoginView, logout_view, RegisterView,
                    GuestRegisterView, AccountHomeView, AccountEmailActivateView,
                    UserDetailUpdateView)
from products.views import UserProductHistoryView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest-register'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
]

src/cart/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^api/$', cart_detail_api_view, name='cart-api'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^checkout/success$',checkout_done_view, name='success'),
    url(r'^checkout/$',checkout_home, name='checkout'),

]

src/mainwebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from .views import home_page, about_page, contact_page
from billing.views import payment_method_view, payment_method_create_view

from marketing.views import MarketingPreferenceUpdateView, MailChimpWebhookView

from addresses.views import (AddressListView, AddressCreateView,
                             AddressUpdateView, checkout_address_reuse_view,
                             checkout_address_create_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls', namespace='password')),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhook/mailchimp/$', MailChimpWebhookView.as_view(), name='webhook-mailchimp'),
    url(r'^cart/', include("cart.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_create_view, name='billing-payment-method-endpoint'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.conf.urls import url

from .views import (
        OrderListView,
        OrderDetailView
        )

urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='list'),
    url(r'^(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='detail'),
]

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User, EmailActivation, GuestEmail
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth import authenticate, login


class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'email'
        })
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password'
        })
    )

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        email = data.get("email")
        password = data.get("password")
        qs = User.objects.filter(email=email)
        if qs.exists():
            # user email is registered, check active/
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                ## not active, check email activation
                link = reverse("account:resend-activation")
                reconfirm_msg = """Go to <a href='{resend_link}'>
                resend confirmation email</a>.
                """.format(resend_link=link)
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")

        user = authenticate(request, username=email, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        self.user = user
        return data


class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password'
    }))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password'
    }))

    email = forms.EmailField(widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'email'
        }))

    full_name = forms.CharField(widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'full name'
        }))

    class Meta:
        model = User
        fields = ('full_name','email', 'password1', 'password2')

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):

        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        if commit:
            user.save()
        return user


class GuestForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'email'
        })
    )

    class Meta:
        model = GuestEmail
        fields = [
            'email'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(GuestForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(GuestForm, self).save(commit=False)
        if commit:
            obj.save()
            request = self.request
            request.session['guest_email_id'] = obj.id
        return obj


class UserAdminCreationForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name')

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):

        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['full_name']


class UserAdminChangeForm(forms.ModelForm):

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'full_name', 'password', 'is_active', 'admin')

    def clean_password(self):
        return self.initial["password"]


class ReactivateEmailForm(forms.Form):
    email = forms.EmailField

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email)
        if not qs.exists():
            register_link = reverse('account:register')

            msg = f"this email does not exists, would you like to <a href='{register_link}'>register </a>?"
            raise forms.ValidationError(mark_safe(msg))
        return email

src/accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import GuestEmail, EmailActivation
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from django.views.generic.edit import FormMixin
from django.conf import settings
from mainwebsite.mixins import NextUrlMixin, RequestFormAttachMixin

# Create your views here.

User = get_user_model()
LOGIN_URL = getattr(settings, 'LOGIN_URL', '/account/login')


class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/account/login/'


def logout_view(request):
    logout(request)
    return redirect('/')


class GuestRegisterView(NextUrlMixin,  RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/account/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = "accounts/home.html"

    def get_object(self, **kwargs):
        return self.request.user


class AccountEmailActivateView(FormMixin, View):
    success_url = LOGIN_URL
    form_class = ReactivateEmailForm
    key = None

    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, 'your email has been confirmed. Please login.')
                return redirect('account:login')
            else:
                activated_qs = qs.filter(key__iexact=key, activated=True)
                if activated_qs.exists():
                    reset_link = reverse('password:password_reset')

                    msg = f""" your email has already been confirmed. 
                    Do you need to <a href='{reset_link}'>reset your password? </a> """

                    messages.success(request, message=mark_safe(msg))
                    return redirect('account:login')
        context = {'form': self.get_form(), 'key':key}
        return render(request, template_name='registration/activation_error.html', context=context)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = f'Activation link sent, please check your email.'
        messages.success(request=self.request, message=msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key}
        return render(self.request, 'registration/activation-error.html', context)


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self, **kwargs):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data()
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")

src/accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-secondary my-3'>Save</button>
  <a href='{% url "password:password_change" %}'>Change Password</a>
</form>
</div>
{% endblock %}

src/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-12" >
        <h1> Account </h1>
        <hr/>
    </div>
    <div class="col-12 col-md-3 my-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Support </h4>
                <div class="list-group">
                    <a class="list-group-item" href='{% url "about" %}'> About</a>
                    <a class="list-group-item" href='{% url "contact" %}'> Contact</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-3 my-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Billing </h4>
                <div class="list-group">
                    <a class="list-group-item" href='{% url "addresses" %}'> Addresses</a>
                    <a class="list-group-item" href='{% url "orders:list" %}'> Orders</a>
                    <a class="list-group-item" href='{% url "billing-payment-method" %}'> Payment Methods</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-3 my-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Account details </h4>
                <div class="list-group">
                    <a class="list-group-item" href='{% url "account:user-update" %}'> Update details </a>
                    <a class="list-group-item" href='{% url "password:password_change"%}'> Change password </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-3 my-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Preferences </h4>
                <div class="list-group">
                    <a class="list-group-item" href='{% url "marketing-pref" %}'> Email Newsletter</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-3 my-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> History </h4>
                 <div class="list-group">
                    <a class="list-group-item" href='{% url "account:user-product-history" %}'> Products Viewed </a>
                 </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
    <div class="col-6 ml-auto mr-auto bg-light" align="center">
        <h1>Login</h1>
            {% include 'accounts/snippets/login-form.html'%}
        <p><a href="{% url 'password:password_reset'%}">forgot password</a> | <a href="{% url 'account:register' %}">register</a></p>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-12 col-md-8 ml-auto mr-auto bg-light" align="center">
            <form class="text-left col-md-6" method="post" style="margin: 5%">{% csrf_token %}
                <h1 class="text-center"> Register </h1><hr/>
            {{ form.as_p }}<br/>
                <div class="col-6 text-center mx-auto">
            <button type="submit" class="btn btn-outline-primary btn-block"> submit </button></div>
                 <p class="text-center">do you need to <a href="{% url 'account:login' %}">login</a> ?</p>
            </form>
        </div>
    </div>
{% endblock %}